name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Linters
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.37
        working-directory: ${{ env.BRANCH }}
    
    - name: TestUnitShort
      run: go test ./... -race -count 100 -short -v
      
    - name: TestUnitAll
      run: go test ./... -race -v

  build:
    needs: verify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build
      run: ./make.sh "0.0.3"

